<!-- Generated by Trae Work -->
<template>
  <!-- 占位容器：只用来计算位置，真正的网页由主进程 BrowserView 渲染在上面 -->
  <div class="deepseek-web-panel" ref="panelRef">
    <div v-if="!viewReady" class="dw-loading">
      <el-icon class="loading-icon"><Loading /></el-icon>
      <span>正在加载 DeepSeek...</span>
      <div class="dw-loading-tip">
        首次加载请先登录账号<br>
        登录后点击右下角 🧠 按钮使用工具
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount, nextTick, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { Loading } from '@element-plus/icons-vue'

const props = defineProps({
  mindMap: { type: Object, default: null },
  currentFilePath: { type: String, default: '' },
  currentFileName: { type: String, default: '' },
  permanentMemory: { type: String, default: '' },
  aiMemory: { type: String, default: '' }
})

const emit = defineEmits(['tool-call', 'switch-mode'])

const panelRef = ref(null)
const viewReady = ref(false)

let resizeObserver = null
let rafId = null
let overlayManuallyHidden = false // 外部手动隐藏标记，防止 ResizeObserver 自动重新显示

// 把容器的屏幕坐标转成窗口坐标（BrowserView 的 bounds 是相对于窗口的）
const updateBounds = async () => {
  if (!panelRef.value) return
  const rect = panelRef.value.getBoundingClientRect()
  
  // 容器不可见时隐藏 BrowserView
  if (rect.width <= 0 || rect.height <= 0) {
    if (window.electronAPI?.deepSeekView && viewReady.value) {
      window.electronAPI.deepSeekView.hide()
    }
    return
  }
  
  const bounds = {
    x: Math.floor(rect.left),
    y: Math.floor(rect.top),
    width: Math.floor(rect.width),
    height: Math.floor(rect.height)
  }
  
  if (window.electronAPI?.deepSeekView) {
    if (viewReady.value) {
      // 已创建：更新位置
      window.electronAPI.deepSeekView.setBounds(bounds)
      // 如果不是被外部手动隐藏的，才自动显示
      // （防止打开日志面板时，ResizeObserver 触发后又把 BrowserView 显示出来）
      if (!overlayManuallyHidden) {
        window.electronAPI.deepSeekView.show()
      }
    } else {
      // 还没创建：创建
      initView()
    }
  }
}

// 用 rAF 节流的更新（避免 ResizeObserver 高频触发 IPC）
const scheduleUpdate = () => {
  if (rafId) return
  rafId = requestAnimationFrame(() => {
    rafId = null
    updateBounds()
  })
}

// 初始化 BrowserView
const initView = async () => {
  if (!window.electronAPI?.deepSeekView) {
    ElMessage.error('DeepSeek 浏览器视图不可用')
    return
  }
  
  if (!panelRef.value) return
  const rect = panelRef.value.getBoundingClientRect()
  
  const bounds = {
    x: Math.floor(rect.left),
    y: Math.floor(rect.top),
    width: Math.floor(rect.width),
    height: Math.floor(rect.height)
  }
  
  try {
    const res = await window.electronAPI.deepSeekView.create(bounds)
    if (res.success) {
      viewReady.value = true
    } else {
      ElMessage.error('DeepSeek 加载失败：' + (res.error || '未知错误'))
    }
  } catch (e) {
    ElMessage.error('DeepSeek 加载失败：' + e.message)
  }
}

// 提取纯文本（去除 HTML 标签）
const getPlainText = (html) => {
  if (!html) return ''
  if (typeof html !== 'string') return String(html)
  const tmp = document.createElement('div')
  tmp.innerHTML = html
  return tmp.textContent || tmp.innerText || ''
}

// 生成上下文文本（只给前 3 层框架，AI 按需用工具查询更深层）
const buildContextText = () => {
  // 每次构建时直接从 localStorage 读最新的永久记忆，不依赖 props 缓存
  // 防止用户在设置面板修改后，ChatPanel 的 memoryText 没有及时同步
  let latestPermanentMemory = props.permanentMemory
  try {
    const stored = localStorage.getItem('ai_memory')
    if (stored !== null && stored.trim()) {
      latestPermanentMemory = stored
    }
  } catch(e) {
    console.warn('[DeepSeekWebPanel] 读取 localStorage 永久记忆失败:', e)
  }
  
  let latestAiMemory = props.aiMemory
  try {
    const stored = localStorage.getItem('ai_memory_facts')
    if (stored) {
      const facts = JSON.parse(stored)
      if (Array.isArray(facts) && facts.length > 0) {
        const factTexts = facts.map(f => `- ${f.content}`).join('\n')
        latestAiMemory = factTexts
      }
    }
  } catch(e) {
    console.warn('[DeepSeekWebPanel] 读取 localStorage AI 记忆失败:', e)
  }
  
  if (!props.mindMap) {
    return '（当前没有打开的思维导图）'
  }
  
  try {
    let nodeCount = 0
    let leafCount = 0
    let maxDepth = 0
    let rootText = ''
    let selectedText = ''
    const outlineLines = []
    const PREVIEW_DEPTH = 3 // 只预览前 3 层
    
    if (props.mindMap?.getData) {
      const root = props.mindMap.getData()
      if (root) {
        // 根节点文本
        rootText = getPlainText(root.data?.text || root.text || '') || '未命名'
        
        const walk = (node, level = 0) => {
          if (!node) return
          nodeCount++
          if (level > maxDepth) maxDepth = level
          const text = getPlainText(node.data?.text || node.text || '')
          const hasChildren = node.children && node.children.length > 0
          if (!hasChildren) leafCount++
          
          // 只输出前 PREVIEW_DEPTH 层
          if (level < PREVIEW_DEPTH && text) {
            const prefix = '#'.repeat(level + 1)
            const moreHint = (level === PREVIEW_DEPTH - 1 && hasChildren) ? ' （还有子节点，可按需查询）' : ''
            outlineLines.push(prefix + ' ' + text + moreHint)
          }
          
          if (node.children) {
            node.children.forEach(child => walk(child, level + 1))
          }
        }
        walk(root)
      }
    }
    
    // 获取当前选中节点
    try {
      const activeNode = props.mindMap.execCommand?.('GetActiveNodeCommand')
      if (activeNode) {
        selectedText = getPlainText(activeNode.data?.text || activeNode.text || '')
      }
    } catch(e) {}
    
    const fileInfo = [
      '## 当前绑定文件',
      `- 文件名：${props.currentFileName || '未命名'}`,
      `- 文件路径：${props.currentFilePath || '（未保存）'}`,
      `- 主题：${rootText || '未命名'}`,
      `- 节点总数：${nodeCount}`,
      `- 叶子节点：${leafCount}`,
      `- 最大层级：${maxDepth + 1} 层`,
      selectedText ? `- 当前选中：「${selectedText}」` : '',
      '',
      `## 导图框架概览（前 ${PREVIEW_DEPTH} 层）`,
      outlineLines.length > 0 ? outlineLines.join('\n') : '（空）',
      '',
      '> 💡 如需查看更深层内容或具体节点信息，请调用 search_nodes、list_directory 等工具按需查询。'
    ].filter(Boolean)
    
    // 添加永久记忆（用户手动设置的，严格遵守）
    if (latestPermanentMemory && latestPermanentMemory.trim()) {
      fileInfo.push('', '## 🔒 永久记忆（严格遵守）', latestPermanentMemory.trim())
    }
    
    // 添加 AI 长期记忆（自然遵循）
    if (latestAiMemory && latestAiMemory.trim()) {
      fileInfo.push('', '## 📝 长期记忆（自然遵循）', latestAiMemory.trim(), '> 只有在用户明确表示需要长期记住的偏好/事实时，才用 save_memory 工具保存。')
    }
    
    return fileInfo.join('\n')
  } catch (e) {
    console.error('获取导图上下文失败:', e)
    return '获取上下文失败：' + (e.message || e)
  }
}

// 上下文发送去重：短时间内相同内容只发一次
let lastSentContextHash = ''
let lastSentContextTime = 0

const sendMindMapContext = (context) => {
  if (!window.electronAPI?.deepSeekView) return
  
  // 去重：1秒内相同内容的上下文只发一次（防止重试 + watcher 双重触发）
  const now = Date.now()
  const hash = context.length + '_' + context.substring(0, 100)
  if (hash === lastSentContextHash && now - lastSentContextTime < 1000) {
    console.log('[DeepSeekWebPanel] 上下文去重：相同内容1秒内只发一次，跳过')
    return
  }
  lastSentContextHash = hash
  lastSentContextTime = now
  
  try {
    console.log('[DeepSeekWebPanel] 发送导图上下文，长度:', context?.length || 0)
    // 发送到 BrowserView 的 preload（通道名不带 deepseek: 前缀）
    window.electronAPI.deepSeekView.send('mindmap-context', context)
  } catch (e) {
    console.error('发送导图上下文失败:', e)
  }
}

// 处理导图上下文请求（带重试：如果 mindMap 暂时为 null，等一下再试）
let contextRetryTimer = null
const handleRequestContext = () => {
  console.log('[DeepSeekWebPanel] 收到上下文请求，props.mindMap:', !!props.mindMap)
  
  // 如果 mindMap 为 null，重试几次（等组件挂载完成）
  if (!props.mindMap) {
    console.warn('[DeepSeekWebPanel] mindMap 为 null，启动重试机制...')
    let retryCount = 0
    const maxRetries = 5
    
    const trySend = () => {
      retryCount++
      if (props.mindMap) {
        console.log(`[DeepSeekWebPanel] 第 ${retryCount} 次重试成功，mindMap 已就绪`)
        sendMindMapContext(buildContextText())
        return
      }
      if (retryCount >= maxRetries) {
        console.warn('[DeepSeekWebPanel] 重试次数用尽，仍无 mindMap，返回空上下文')
        sendMindMapContext('（当前没有打开的思维导图）')
        return
      }
      console.log(`[DeepSeekWebPanel] 第 ${retryCount} 次重试，mindMap 仍为 null，继续等待...`)
      contextRetryTimer = setTimeout(trySend, 500)
    }
    
    if (contextRetryTimer) clearTimeout(contextRetryTimer)
    contextRetryTimer = setTimeout(trySend, 300)
    return
  }
  
  sendMindMapContext(buildContextText())
}

// 监听 mindMap 变化：只有在有未完成的上下文请求（重试中）时才补发
watch(() => props.mindMap, (newMindMap, oldMindMap) => {
  if (newMindMap && !oldMindMap) {
    console.log('[DeepSeekWebPanel] mindMap 从 null 变为有值')
    // 如果有正在进行的重试，取消重试并直接发送
    if (contextRetryTimer) {
      clearTimeout(contextRetryTimer)
      contextRetryTimer = null
      if (viewReady.value && window.electronAPI?.deepSeekView) {
        sendMindMapContext(buildContextText())
      }
    }
    // 注意：正常的 mindMap 变化（如切换文件）不自动发送上下文，
    // 避免用户只是浏览文件时被打扰。用户可手动点初始化按钮更新。
  }
}, { deep: false })

// 注意：已移除文件路径变化时自动发送上下文的逻辑
// 原因：用户切换文件浏览时不应该被自动初始化打扰
// 用户需要时可手动点击"初始化"按钮更新绑定文件

const sendToolResult = (toolId, result, error) => {
  if (!window.electronAPI?.deepSeekView) {
    console.error('[DeepSeekWebPanel] sendToolResult: deepSeekView API 不存在')
    return
  }
  if (typeof window.electronAPI.deepSeekView.send !== 'function') {
    console.error('[DeepSeekWebPanel] sendToolResult: deepSeekView.send 不是函数', typeof window.electronAPI.deepSeekView.send)
    return
  }
  try {
    console.log('[DeepSeekWebPanel] 发送工具结果:', toolId, 'error:', error)
    // 发送到 BrowserView 的 preload（通道名不带 deepseek: 前缀）
    window.electronAPI.deepSeekView.send('tool-result', { toolId, result, error })
  } catch (e) {
    console.error('发送工具结果失败:', e)
  }
}

// 处理工具执行请求（来自 BrowserView preload → 主进程转发 → 这里）
// 注意：emit 不返回结果，由父组件 ChatPanel 处理后通过 sendToolResult 回传
const handleToolCall = async (data) => {
  const { toolId, name, params } = data || {}
  console.log('[DeepSeekWebPanel] 收到工具调用:', toolId, name, params)
  try {
    // 父组件会监听 tool-call 事件，处理完后调用 sendToolResult 回传结果
    emit('tool-call', { toolId, name, params })
  } catch (e) {
    console.error('[DeepSeekWebPanel] 工具调用分发失败:', e)
    sendToolResult(toolId, null, e.message || '分发失败')
  }
}

// 监听清理函数
let removeRequestContext = null
let removeExecuteTool = null
let removeConsoleLog = null
let removeIpcDebug = null

onMounted(async () => {
  await nextTick()
  
  // 初始化 BrowserView
  initView()
  
  // 监听来自 BrowserView 的消息（主进程转发，通道名带 deepseek: 前缀）
  if (window.electronAPI?.deepSeekView?.onMessage) {
    removeRequestContext = window.electronAPI.deepSeekView.onMessage(
      'deepseek:request-context',
      () => handleRequestContext()
    )
    removeExecuteTool = window.electronAPI.deepSeekView.onMessage(
      'deepseek:execute-tool',
      (data) => handleToolCall(data)
    )
    // 接收 BrowserView 的控制台日志（转发到主窗口控制台）
    removeConsoleLog = window.electronAPI.deepSeekView.onMessage(
      'deepseek:console-log',
      (data) => {
        const { level, message, line, sourceId } = data
        const prefix = '%c[DeepSeek] '
        const style = 'color: #007aff; font-weight: bold;'
        if (level === 'error') {
          console.error(prefix + message + ` (${sourceId}:${line})`, style)
        } else if (level === 'warn') {
          console.warn(prefix + message + ` (${sourceId}:${line})`, style)
        } else {
          console.log(prefix + message, style)
        }
      }
    )
    // 接收主进程的 IPC 调试日志
    removeIpcDebug = window.electronAPI.deepSeekView.onMessage(
      'deepseek:ipc-debug',
      (msg) => {
        console.log('%c[DeepSeek IPC] ' + msg, 'color: #ff9500; font-weight: bold;')
      }
    )
  }
  
  // 监听容器尺寸变化
  if (typeof ResizeObserver !== 'undefined' && panelRef.value) {
    resizeObserver = new ResizeObserver(() => {
      scheduleUpdate()
    })
    resizeObserver.observe(panelRef.value)
  }
  
  // 窗口 resize 时也更新
  window.addEventListener('resize', scheduleUpdate)
  
  // 滚动时也要更新位置（容器可能随滚动移动）
  window.addEventListener('scroll', scheduleUpdate, true)
})

onBeforeUnmount(() => {
  if (rafId) {
    cancelAnimationFrame(rafId)
    rafId = null
  }
  if (resizeObserver) {
    resizeObserver.disconnect()
    resizeObserver = null
  }
  window.removeEventListener('resize', scheduleUpdate)
  window.removeEventListener('scroll', scheduleUpdate, true)
  
  // 清理 IPC 监听
  if (removeRequestContext) {
    removeRequestContext()
    removeRequestContext = null
  }
  if (removeExecuteTool) {
    removeExecuteTool()
    removeExecuteTool = null
  }
  if (removeConsoleLog) {
    removeConsoleLog()
    removeConsoleLog = null
  }
  if (removeIpcDebug) {
    removeIpcDebug()
    removeIpcDebug = null
  }
  
  // 清理定时器
  if (contextRetryTimer) {
    clearTimeout(contextRetryTimer)
    contextRetryTimer = null
  }
  
  // 隐藏 BrowserView（不销毁，保留登录状态）
  if (window.electronAPI?.deepSeekView) {
    window.electronAPI.deepSeekView.hide()
  }
})

// 外部控制显示/隐藏（设置弹窗等打开时调用）
const setOverlayVisible = (visible) => {
  if (!window.electronAPI?.deepSeekView || !viewReady.value) return
  if (visible) {
    overlayManuallyHidden = false
    // 显示时延迟更新位置，等 DOM 布局稳定后再计算（比如日志面板刚关闭，容器宽度会变）
    // 用 nextTick + 双 rAF 确保布局已完成
    nextTick(() => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          updateBounds()
          window.electronAPI.deepSeekView.show()
        })
      })
    })
  } else {
    overlayManuallyHidden = true
    window.electronAPI.deepSeekView.hide()
  }
}

defineExpose({ setOverlayVisible, sendToolResult })
</script>

<style scoped>
.deepseek-web-panel {
  width: 100%;
  height: 100%;
  position: relative;
  background: #fff;
  overflow: hidden;
}

.dw-loading {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  color: #909399;
  font-size: 14px;
  background: #f5f5f5;
  z-index: 1;
}

.dw-loading .loading-icon {
  font-size: 36px;
  color: #409eff;
  animation: spin 1.5s linear infinite;
}

.dw-loading-tip {
  font-size: 12px;
  color: #c0c4cc;
  text-align: center;
  line-height: 1.6;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
</style>
